[Target]
# The exact name of the executable you want to mod (e.g. YourGame, sekiro, DarkSoulsIII, eldenring)
ProcessName=sekiro

[Memory]
# Base Offset for the Camera Pointer (Hex)
CameraBaseOffset=0x03D5C000

# Comma-separated list of pointer chain offsets to reach the Camera Struct (Hex)
CameraOffsets=0x20,0x58,0x8,0x10

[HeadTracking]
; Mode can be 'Memory' (6DOF Native) or 'Mouse' (Universal 3DOF)
Mode=Mouse
MouseSensitivityX=1000.0
MouseSensitivityY=1000.0
InvertY=false

[Debug]
# Set to true to force VR split-screen rendering on your desktop even without a headset
ForceSplitScreen=true

[MotionControllers]
Enabled=false
; Pointer chain to reach the local player character
PlayerBaseOffset=041D3A00
PlayerOffsets=10,28,68
; Offset from Player Character to the Bone Transform Matrix Array (Havok)
BoneArrayOffset=0x8A0
; Index of the right hand/sword bone in the array
RightHandBoneIndex=42
; Index of the left hand/deflect bone in the array
LeftHandBoneIndex=43
